group = 'Editor UI'

apply plugin: 'org.openjfx.javafxplugin'

javafx {
    version = "21"
    modules = [ 'javafx.fxml', 'javafx.controls', 'javafx.media', 'javafx.swing']
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }
    dependencies {
        // provides javafx-gradle-plugin
       // classpath group: 'de.dynamicfiles.projects.gradle.plugins', name: 'javafx-gradle-plugin', version: "8.8.2"
        // provides proguard.gradle.ProGuardTask (including all requirements)
        classpath 'net.sf.proguard:proguard-gradle:6.1.1'
    }
}

apply plugin: 'application'
//apply plugin: 'org.beryx.runtime'

run {
	standardInput = System.in
	jvmArgs = [
		'--add-opens', 'javafx.graphics/com.sun.javafx.css=ALL-UNNAMED',
		'--add-opens', 'javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED',
		'--add-opens', 'javafx.controls/com.sun.javafx.scene.control=ALL-UNNAMED',
		'--add-opens', 'javafx.base/com.sun.javafx.binding=ALL-UNNAMED',
		'--add-opens', 'javafx.base/com.sun.javafx.event=ALL-UNNAMED',
		'--add-opens', 'javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED',
		'--add-opens', 'javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED'
	]
}
// In this section you declare the dependencies for your production and test code
dependencies  {

 	implementation project(':Client')
	implementation project(':RS-Cache-Library')
	// https://mvnrepository.com/artifact/org.controlsfx/controlsfx
	implementation('org.controlsfx:controlsfx:11.2.1') {
		exclude group: 'org.openjfx'
	}
	implementation 'com.jfoenix:jfoenix:8.0.9'
	
	// Add missing dependencies that Editor uses
	implementation group: 'org.apache.commons', name: 'commons-math3', version: '3.6.1'
	implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.1'
	implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.1'
	implementation group: 'net.coobird', name: 'thumbnailator', version: '0.4.8'
	implementation group: 'org.greenrobot', name: 'eventbus', version: '3.1.1'
	implementation group: 'org.quartz-scheduler', name: 'quartz', version: '2.3.0'


}



jar {
	archiveFileName = "Editor.jar"
	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
	manifest {
		attributes(
			'Main-Class': 'com.rspsi.LauncherWindow'
			
		)
	}
    from configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it).matching{ exclude{it.path.contains('META-INF') } } }

}


task myProguardTask(type: proguard.gradle.ProGuardTask) {
    configuration 'proguard.conf'
    
    
    libraryjars project.sourceSets.main.compileClasspath
    

	if (JavaVersion.current().java9Compatible) {
	    libraryjars(System.getProperty("java.home") + "/jmods")
	} else {
	    libraryjars(System.getProperty("java.home") + "/lib/rt.jar")
	    libraryjars(System.getProperty("java.home") + "/lib/ext/jfxrt.jar")
	}
	
	
    injars 'build/libs/Editor.jar'
    outjars 'build/libs/deploy/Editor.jar'
}

application {
    mainClass = "com.rspsi.LauncherWindow"
    applicationName = 'RSPSi'
}
//defaultTask 'jar'



/*runtime {
	javaHome = 'F:/jdks/windows/jdk-11.0.3.7-hotspot'
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = ['java.sql',
				'java.naming',
				'java.logging',
				'java.management',
				'java.xml',
				'jdk.unsupported',
				'java.desktop',
				'java.scripting',
				'jdk.unsupported.desktop',
				'java.datatransfer']
				 targetPlatform('linux', 'F:/jdks/linux/jdk-11.0.3+7-jre')
				 targetPlatform('win', 'F:/jdks/windows/jdk-11.0.3.7-hotspot')
				 targetPlatform('mac', 'F:/jdks/mac/jdk-11.0.3+7')
				 
				 jpackage {
					jpackageHome = "F:/jdks/windows/jdk-11.0.3.7-hotspot"
					imageOutputDir = file("$buildDir/my-packaging-image")
					installerOutputDir = file("$buildDir/my-packaging-installer")
					targetPlatformName = "win"
				}
}*/

//jar.finalizedBy(myProguardTask)